name: Actualizador automatico FIRMS

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el proyecto
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar librerias espaciales
      run: |
        pip install pandas geopandas shapely fiona requests

    - name: Procesar fuegos
      run: python tracker.py

    - name: Publicar el mapa actualizado de forma segura
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Sincronizacion automatica de mapas"
        file_pattern: 'output/*.geojson'
